### ISSUE TITLE
在微信群里连续两次撤回信息回报错

### ISSUE THREAD

**Issue by wakerman** [HanSon/vbot#103]
问题重现
在微信群里发信息，比如【你好】然后撤销【你好】，返回信息之后，再次撤销返回的信息就报错了

**Comment by HanSon** [comment]
你意思是机器人自己去撤回消息吗？

**Comment by wakerman** [comment]
不是，都是人为撤销。
>
在微信群里发信息，比如【你好】然后人为撤销【你好】，机器人返回人为撤销的【你好】信息之后，再次人为的撤销刚才机器人返回的信息就报错了

**Comment by HanSon** [comment]
现在撤回应该没有问题了
