### ISSUE TITLE
可不可以有主动退群，主动删好友的功能呢？

### ISSUE THREAD

**Issue by w7851435** [HanSon/vbot#108]
随着群的增多，好友增多，变的不太稳定了，一会就自动退了，目测是腾讯有限制了，希望能有自动退群，删好友的功能

**Comment by HanSon** [comment]
其实是这两天微信的改动导致不稳定

**Comment by w7851435** [comment]
又什么解决办法没有呢？

**Comment by HanSon** [comment]
有个设想方案，今天在测试

**Comment by w7851435** [comment]
我也是php多年从业者，但是完全读懂这个代码还是有难度，一般的学习教程什么的基本都会，可以指点一下该从什么方向学习么？可以帮你们一起开发么？

**Comment by HanSon** [comment]
如果对 symfony 的 console 比较熟悉可以去想想 2.0 版本的命令模块

2.0 将以命令或者 API 的形式进行方法调用

**Comment by HanSon** [comment]
删好友实现不了，现在版本也已经稳定
