### ISSUE TITLE
[2017-05-11 11:03:30][INFO] ret:1101

### ISSUE THREAD

**Issue by blusewang** [HanSon/vbot#121]
[abc] [2017-05-11 11:03:06][INFO] 请扫描二维码登录
[abc] [2017-05-11 11:03:16][INFO] 请点击确认登录微信
[abc] [2017-05-11 11:03:18][INFO] 登录成功
[abc] [2017-05-11 11:03:19][INFO] 当前用户昵称：Peter总监
[abc] [2017-05-11 11:03:19][INFO] 当前用户ID：@35fe2a5c5be8beb827cec814dd462791420fce694dfbad693b6952b826b6ef96
[abc] [2017-05-11 11:03:19][INFO] 当前用户UIN：298635220
[abc] [2017-05-11 11:03:24][INFO] 初始化成功
[abc] [2017-05-11 11:03:24][INFO] 当前session：abc
[abc] [2017-05-11 11:03:24][INFO] 开始初始化联系人
[abc] [2017-05-11 11:03:29][INFO] 初始化联系人成功
[abc] [2017-05-11 11:03:29][INFO] 群数量： 4
[abc] [2017-05-11 11:03:29][INFO] 联系人数量： 110
[abc] [2017-05-11 11:03:29][INFO] 公众号数量： 3
[abc] [2017-05-11 11:03:30][INFO] ret:1101
[abc] [2017-05-11 11:03:30][INFO] ret:1101
[abc] [2017-05-11 11:03:31][INFO] ret:1101
[abc] [2017-05-11 11:03:31][INFO] ret:1101
[abc] [2017-05-11 11:03:31][INFO] ret:1101
[abc] [2017-05-11 11:03:32][INFO] ret:1101
[abc] [2017-05-11 11:03:32][INFO] ret:1101
[abc] [2017-05-11 11:03:33][INFO] ret:1101
[abc] [2017-05-11 11:03:33][INFO] ret:1101
[abc] [2017-05-11 11:03:33][INFO] ret:1101
[abc] [2017-05-11 11:03:34][INFO] ret:1101
[abc] [2017-05-11 11:03:34][INFO] ret:1101
[abc] [2017-05-11 11:03:35][INFO] ret:1101
[abc] [2017-05-11 11:03:35][INFO] ret:1101
[abc] [2017-05-11 11:03:35][INFO] ret:1101
[abc] [2017-05-11 11:03:36][INFO] ret:1101
[abc] [2017-05-11 11:03:36][INFO] ret:1101
[abc] [2017-05-11 11:03:36][INFO] ret:1101
[abc] [2017-05-11 11:03:37][INFO] ret:1101

谁知道这是为什么？

**Comment by blusewang** [comment]
同步失败，源码里抛了异常，你自己又把它丢掉了。
也没个处理的入口。
急得我想改源码

**Comment by HanSon** [comment]
尝试一下 master 分支 的最新代码试试

**Comment by blusewang** [comment]
@HanSon 噢！
