### ISSUE TITLE
控制台输出都是乱码

### ISSUE THREAD

**Issue by guanbiao33** [HanSon/vbot#136]
rt,控制台输出都是乱码，请问怎么解决？

**Comment by HanSon** [comment]
乱码请自行 百度、google 乱码解决方法

**Comment by huanglike** [comment]
@guanbiao33  你的控制台的乱码问题解决了吗？我按照谷歌的结果其他地方原来出现中文乱码的地方都已经解决了，只有启动了Vbot后输出的中文还是乱码，比较郁闷。
