### ISSUE TITLE
自定义发送消息接口没有吗

### ISSUE THREAD

**Issue by gongcheng121** [HanSon/vbot#14]
比如我在其他的地方使用Text::send(); 实现发送消息

**Comment by HanSon** [comment]
Text::send()就是[消息发送的接口](https://github.com/HanSon/vbot/wiki/%E6%96%87%E5%AD%97%20Text#%E6%96%B9%E6%B3%95)

**Comment by gongcheng121** [comment]
嗯，那个我看了，我的意思是在另外的运行实例中，是不能直接使用的。当然监听消息的接口很完整，只是如果我需要非回掉的方式直接发送消息。

**Comment by HanSon** [comment]
可以看看`setCustomHandler`是否适合自己的需求。

缓存不是重点，重点是重新登录时微信网页端强制需要的，始终需要登录
