### ISSUE TITLE
执行 php example/run.php --session=vbot 报错

### ISSUE THREAD

**Issue by holyen** [HanSon/vbot#146]
'''
vbot.ERROR: Undefined index: skey [] []
PHP Fatal error:  Uncaught ErrorException: Undefined index: skey in /xxxx/vbot/src/Core/Server.php:191
Stack trace:
#0 /xxxx/vbot/src/Core/Server.php(191): Hanson\Vbot\Foundation\ExceptionHandler->handleError(8, 'Undefined index...', '/data/wwwroot/d...', 191, Array)
#1 /xxxx/vbot/src/Core/Server.php(91): Hanson\Vbot\Core\Server->getLogin()
#2 /xxxx/vbot/src/Core/Server.php(34): Hanson\Vbot\Core\Server->login()
#3 /xxxx/vbot/example/Example.php(36): Hanson\Vbot\Core\Server->serve()
#4 /xxxx/vbot/example/run.php(9): Hanson\Vbot\Example\Example->run()
#5 {main}
  thrown in /xxxx/vbot/src/Core/Server.php on line 191

Fatal error: Uncaught ErrorException: Undefined index: skey in /xxxx/vbot/src/Core/Server.php:191
Stack trace:
#0 /xxxx/vbot/src/Core/Server.php(191): Hanson\Vbot\Foundation\ExceptionHandler->handleError(8, 'Undefined index...', '/data/wwwroot/d...', 191, Array)
#1 /xxxx/vbot/src/Core/Server.php(91): Hanson\Vbot\Core\Server->getLogin()
#2 /xxxx/vbot/src/Core/Server.php(34): Hanson\Vbot\Core\Server->login()
#3 /xxxx/vbot/example/Example.php(36): Hanson\Vbot\Core\Server->serve()
#4 /xxxx/vbot/example/run.php(9): Hanson\Vbot\Example\Example->run()
#5 {main}
  thrown in /xxxx/vbot/src/Core/Server.php on line 191
[2017-06-03 12:53:02] vbot.ERROR: Uncaught ErrorException: Undefined index: skey in /xxxx/vbot/src/Core/Server.php:191 Stack trace: #0 /xxxx/vbot/src/Core/Server.php(191): Hanson\Vbot\Foundation\ExceptionHandler->handleError(8, 'Undefined index...', '/data/wwwroot/d...', 191, Array) #1 /xxxx/vbot/src/Core/Server.php(91): Hanson\Vbot\Core\Server->getLogin() #2 /xxxx/vbot/src/Core/Server.php(34): Hanson\Vbot\Core\Server->login() #3 /xxxx/vbot/example/Example.php(36): Hanson\Vbot\Core\Server->serve() #4 /xxxx/vbot/example/run.php(9): Hanson\Vbot\Example\Example->run() #5 {main}   thrown [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: Undefined index: skey in /xxxx/vbot/src/Core/Server.php:191
Stack trace:
#0 /xxxx/vbot/src/Core/Server.php(191): Hanson\Vbot\Foundation\ExceptionHandler->handleError(8, 'Undefined index...', '/data/wwwroot/d...', 191, Array)
#1 /xxxx/vbot/src/Core/Server.php(91): Hanson\Vbot\Core\Server->getLogin()
#2 /xxxx/vbot/src/Core/Server.php(34): Hanson\Vbot\Core\Server->login()
#3 /xxxx/vbot/example/Example.php(36): Hanson\Vbot\Core\Server->serve()
#4 /xxxx/vbot/example/run.php(9): Hanson\Vbot\Example\Example->run()
#5 {main}
  thrown in /xxxx/vbot/src/Core/Server.php:191
Stack trace:
#0 {main}
  thrown in /xxxx/vbot/src/Core/Server.php on line 191

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: Undefined index: skey in /xxxx/vbot/src/Core/Server.php:191
Stack trace:
#0 /xxxx/vbot/src/Core/Server.php(191): Hanson\Vbot\Foundation\ExceptionHandler->handleError(8, 'Undefined index...', '/data/wwwroot/d...', 191, Array)
#1 /xxxx/vbot/src/Core/Server.php(91): Hanson\Vbot\Core\Server->getLogin()
#2 /xxxx/vbot/src/Core/Server.php(34): Hanson\Vbot\Core\Server->login()
#3 /xxxx/vbot/example/Example.php(36): Hanson\Vbot\Core\Server->serve()
#4 /xxxx/vbot/example/run.php(9): Hanson\Vbot\Example\Example->run()
#5 {main}
  thrown in /xxxx/vbot/src/Core/Server.php:191
Stack trace:
#0 {main}
  thrown in /xxxx/vbot/src/Core/Server.php on line 191

'''

**Comment by HanSon** [comment]
版本号？

**Comment by holyen** [comment]
直接用master上代码 @HanSon

**Comment by HanSon** [comment]
账号异常

**Comment by shouhuori** [comment]
<error><ret>1203</ret><message>For account security, newly registered WeChat accounts are unable to log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wechat.com</message></error>
