### ISSUE TITLE
能否自动，定时在群里发送信息

### ISSUE THREAD

**Issue by lulinha** [HanSon/vbot#149]
看着一些淘客群能每隔10分钟自动发送一条优惠信息。

**Comment by HanSon** [comment]
可以在接受到消息时判断是否间隔10分钟然后自行发送

**Comment by springjk** [comment]
也可以使用 swoole 的定时器，或者通过 crontab 请求 swoole 启动后的 http api 推送消息。

**Comment by noikiy** [comment]
@springjk swoole版本有要求吗？我用的2.0+的，vbot都运行不起来

**Comment by springjk** [comment]
@noikiy 我是通过 `pecl install swoole` 安装的，看官网发布应该属于 `1.9.*`, `2.*` 还没有 stable，我没有测试过，建议你使用 `pecl` 发行版。
