### ISSUE TITLE
能否将消息发送到指定的群?

### ISSUE THREAD

**Issue by zacksleo** [HanSon/vbot#157]
使用Swoole API进行主动推送消息时, 能否将消息发送到指定的群?

**Comment by HanSon** [comment]
![image](https://user-images.githubusercontent.com/10583423/27000881-23317f0c-4dee-11e7-9078-bcd2b1a31db5.png)

**Comment by zacksleo** [comment]
username 是群名?

**Comment by HanSon** [comment]
这是基础了，文档各个地方都有 username （联系人、消息等）

**Comment by zacksleo** [comment]
根据文档中的说明, username指的是用户的username, 然后群并没有类似属性, 接口的描述中, 只看出来可以发送给单个用户, 我是意思是怎样往指定的群发消息(群发)? 例如根据群名群发消息,  能否说详细一些, 谢谢

**Comment by HanSon** [comment]
群是有的，群发的话遍历即可

**Comment by HanSon** [comment]
username 这块我会在文档中加强补充

**Comment by HanSon** [comment]
用户、公众号、群，都有自己的 username

**Comment by zacksleo** [comment]
谢谢 👍
