### ISSUE TITLE
即使gd已安装，登陆时无法看到二维码

### ISSUE THREAD

**Issue by lightpencil** [HanSon/vbot#171]
![image](https://user-images.githubusercontent.com/19776029/27369539-f2714b36-568a-11e7-99ad-7bfc7a68b424.png)
```php -m
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
standard
swoole
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zlib

[Zend Modules]
```
ssh远程 软件为xshell

**Comment by HanSon** [comment]
gd 与 是否显示二维码无关，gd库只是决定了能否执行显示图片的模块代码，是否显示图片取决于 terminal，详情 google ANSI color

**Comment by lightpencil** [comment]
已找到解决办法，贴出供参考：
若不显示二维码，把登陆链接在第三方平台转换一下，扫描即可登陆。
微信内直接点击无效。

**Comment by chichumeng** [comment]
同样遇到这个问题,已解决
环境 centos7 php7.1
解决方案 
安装posix就解决了.

不建议"google ANSI color"  很绕弯子,没直接解决方案

**Comment by HanSon** [comment]
@chichumeng 谢谢分享

**Comment by Baogaitou** [comment]
补充 Package name:  php71-php-process
