### ISSUE TITLE
文件消息包含回车时message['pure'] 获取内容不全

### ISSUE THREAD

**Issue by tmkdahko** [HanSon/vbot#172]
文件: Hanson\Vbot\Message Text.php
$isMatch = preg_match('/@(.+?)\s(.+)/', $content, $match);
return $isMatch ? $match[2] : $this->message;
这一行代码，当$content包含有换行符时，$match[2]的内容会从换行符处截断。。

建议修改成
preg_match('/^@(.+?)\s([\s\S]*)/', $content, $match);

**Comment by HanSon** [comment]
新版本已修复
