### ISSUE TITLE
verifyUser 失效了

### ISSUE THREAD

**Issue by guyueyingmu** [HanSon/vbot#184]
/**
     * 验证通过好友.
     *
     * @param $code
     * @param $userList
     * @param null $content
     *
     * @return bool
     */
    public function verifyUser($code, $userList, $content = '')

BaseRequest参数顺序和原来不一样，调整之后也无效

**Comment by HanSon** [comment]
更新新版本即可

**Comment by guyueyingmu** [comment]
更新之后好了，谢谢
