### ISSUE TITLE
发送消息偶尔会报错，但是还是发送成功

### ISSUE THREAD

**Issue by charlesyq** [HanSon/vbot#185]
报错如下：
ERROR	swFactoryProcess_finish (ERROR 1004): send 199 byte failed, because connection[fd=18] is closed.
这是为啥呢

**Comment by 96qbhy** [comment]
这是因为指定 fd (客户端链接唯一标识) 的链接已经断开。有可能是超时造成的。具体看业务。

**Comment by charlesyq** [comment]
我是隔一会儿调用发消息的接口就会报这个错，消息是发送成功了，但是没有返回请求的结果，有什么办法解决么，没返回结果我就没法判断消息是否发送成功了 @96qbhy

**Comment by HanSon** [comment]
https://github.com/swoole/swoole-src/issues/650

**Comment by charlesyq** [comment]
把swoole 换成2.0 的版本就不会有这个问题了
