### ISSUE TITLE
验证通过好友异常，提示 Argument pass error

### ISSUE THREAD

**Issue by codejm** [HanSon/vbot#186]
目前自动通过好友出错，提示 Argument pass error，打印请求如下：

**url：**

string(143) "https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxverifyuser?lang=zh_CN&r=1499166910000&pass_ticket=Qq8Sj8YH6MzlImDTqISvvG21%2F5%2F96hCDzftn1NsdauI%3D"

**data:**
array(8) {
  ["BaseRequest"]=>
  array(4) {
    ["Uin"]=>
    string(8) "61936965"
    ["Sid"]=>
    string(16) "5NP9CUmqsDJ0Q1rZ"
    ["Skey"]=>
    string(48) "@crypt_cc359372_caca96802da3f009e078bfdb14a36ae8"
    ["DeviceID"]=>
    string(16) "e979483881952455"
  }
  ["Opcode"]=>
  int(3)
  ["VerifyUserListSize"]=>
  int(1)
  ["VerifyUserList"]=>
  array(2) {
    ["Value"]=>
    string(65) "@6eaf037979a5907b294ce7c9f61e3250f125e594e14d9bc88f43ecf042dc9d78"
    ["VerifyUserTicket"]=>
    string(140) "v2_d7876365cf07d9cfffabeca1149c2782928cb9f507546623535bb4bcd470adead8df9a8cd26a1796715a0e4248eb599079ba1d3508fbfc38ce9e500fc2a98ed9@stranger"
  }
  ["VerifyContent"]=>
  NULL
  ["SceneListCount"]=>
  int(1)
  ["SceneList"]=>
  array(1) {
    [0]=>
    int(33)
  }
  ["skey"]=>
  string(48) "@crypt_cc359372_caca96802da3f009e078bfdb14a36ae8"
}

**result:**
array(1) {
  ["BaseResponse"]=>
  array(2) {
    ["Ret"]=>
    int(1)
    ["ErrMsg"]=>
    string(0) ""
  }
}

**Comment by HanSon** [comment]
更新到最新版本即可
