### ISSUE TITLE
一运行就报一堆错误，是不是我哪操作错了？

### ISSUE THREAD

**Issue by thinkmoon** [HanSon/vbot#187]
vbot.ERROR: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php on line 31 [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php on line 31 in C:\vbot\vendor\illuminate\redis\RedisManager.php:38
Stack trace:
#0 C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 C:\vbot\vendor\illuminate\container\Container.php(726): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 C:\vbot\vendor\illuminate\container\Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#3 C:\vbot\vendor\illuminate\container\Container.php(575): Illuminate\Container\Container->resolve('redis')
#4 C:\vbot\vendor\illuminate\container\Container.php(1172): Illuminate\Container\C in C:\vbot\vendor\illuminate\redis\RedisManager.php on line 38

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php on line 31 in C:\vbot\vendor\illuminate\redis\RedisManager.php:38
Stack trace:
#0 C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 C:\vbot\vendor\illuminate\container\Container.php(726): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 C:\vbot\vendor\illuminate\container\Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#3 C:\vbot\vendor\illuminate\container\Container.php(575): Illuminate\Container\Container->resolve('redis')
#4 C:\vbot\vendor\illuminate\container\Container.php(1172): Illuminate\Container\C in C:\vbot\vendor\illuminate\redis\RedisManager.php on line 38
[2017-07-05 03:42:39] vbot.ERROR: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php on line 31 in C:\vbot\vendor\illuminate\redis\RedisManager.php:38 Stack trace: #0 C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL) #1 C:\vbot\vendor\illuminate\container\Container.php(726): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array) #2 C:\vbot\vendor\illuminate\container\Container.php(608): Illuminate\Container\Container->build(Object(Closure)) #3 C:\vbot\vendor\illuminate\container\Container.php(575): Illuminate\Container\Container->resolve('redis') #4 C:\vbot\vendor\illuminate\container\Container.php(1172): Illuminate\Container\C [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php on line 31 in C:\vbot\vendor\illuminate\redis\RedisManager.php:38
Stack trace:
#0 C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 C:\vbot\vendor\illuminate\container\Container.php(726): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 C:\vbot\vendor\illuminate\container\Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#3 C:\vbot\vendor\illuminate\container\Container.php(575): Illuminate\Container\Container->resolve('redis')
#4 C:\vbot\vendor\ in C:\vbot\vendor\illuminate\redis\RedisManager.php on line 38

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php on line 31 in C:\vbot\vendor\illuminate\redis\RedisManager.php:38
Stack trace:
#0 C:\vbot\vendor\hanson\vbot\src\Foundation\ServiceProviders\CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 C:\vbot\vendor\illuminate\container\Container.php(726): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 C:\vbot\vendor\illuminate\container\Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#3 C:\vbot\vendor\illuminate\container\Container.php(575): Illuminate\Container\Container->resolve('redis')
#4 C:\vbot\vendor\ in C:\vbot\vendor\illuminate\redis\RedisManager.php on line 38

**Comment by HanSon** [comment]
redis 配置有问题

**Comment by thinkmoon** [comment]
啊？那是要怎么配置？redis我不知道怎么配置？要么说个大致方向，我去谷歌？

**Comment by bear-shen** [comment]
`
			'database'  => [
				'redis' => [
					'default' => [
						'host'     => 'localhost',
						'port'     => 6379,
						'database' => 1,
					],
				],
			],
`
翻了小半天代码……大概这样并排加在cache那一排的配置里就行……………………laravel用户应该很熟，其他的……………………
