### ISSUE TITLE
能不能一次性开多个微信呢，能不能提供一下思路

### ISSUE THREAD

**Issue by lk3407105** [HanSon/vbot#189]
就目前测试的情况看，一切都正常，就是在如果登录一个帐号之后，还想登录其他的帐号，要怎么实现。session值在启动的时候设置过，如果在次登录的时候会不会出现session冲突的情况，目前也不知道要怎么测试。

**Comment by HanSon** [comment]
你不会换一个 session 值么。。

**Comment by lk3407105** [comment]
非常感谢，目前对项目还没有太深入的了解，看文档上面启动是 php run.php --session=vbot.这是不是就是指定session键值就是vbot了，还是说这里的vbot只是键值的前缀之类的。

**Comment by HanSon** [comment]
只是自己设定的键值

**Comment by lk3407105** [comment]
好的谢谢，我在深入学习一下这个项目程序，看到这个项目的时候真的让我思路一下子开阔很多

**Comment by HanSon** [comment]
不客气，加油
