### ISSUE TITLE
扫描超时报错 LoginTimeoutException

### ISSUE THREAD

**Issue by guoxiangke** [HanSon/vbot#190]
`Fatal error: Uncaught Hanson\Vbot\Exceptions\LoginTimeoutException: Login time out. in /app/vendor/hanson/vbot/src/Core/Server.php:179

ace:
#0 /app/vendor/hanson/vbot/src/Core/Server.php(92): Hanson\Vbot\Core\Server->waitForLogin()
#1 /app/vendor/hanson/vbot/src/Core/Server.php(35): Hanson\Vbot\Core\Server->login()
#2 /app/src/wechat/Wechat.php(51): Hanson\Vbot\Core\Server->serve()
#3 /app/src/wechat/run.php(9): Dale\Vbot\Wechat\Wechat->run()

}
  thrown in /app/vendor/hanson/vbot/src/Core/Server.php on line 179

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Hanson\Vbot\Exceptions\LoginTimeoutException: Login time out. in /app/vendor/hanson/vbot/src/Core/Server.php:179

ace:
#0 /app/vendor/hanson/vbot/src/Core/Server.php(92): Hanson\Vbot\Core\Server->waitForLogin()
#1 /app/vendor/hanson/vbot/src/Core/Server.php(35): Hanson\Vbot\Core\Server->login()
#2 /app/src/wechat/Wechat.php(51): Hanson\Vbot\Core\Server->serve()
#3 /app/src/wechat/run.php(9): Dale\Vbot\Wechat\Wechat->run()

}
  thrown in /app/vendor/hanson/vbot/src/Core/Server.php:179

ace:

}
  thrown in /app/vendor/hanson/vbot/src/Core/Server.php on line 179`

**Comment by HanSon** [comment]
这是 Vbot 抛的异常，有什么问题？
