### ISSUE TITLE
建议在控制台打印一下二维码地址 会更加灵活

### ISSUE THREAD

**Issue by DanceSmile** [HanSon/vbot#194]

**Comment by HanSon** [comment]
这个可以自行实现 http://create.hanc.cc/vbot/docs/observer.html#二维码监听器

**Comment by DanceSmile** [comment]
https://login.weixin.qq.com/l/gdiDGrQX8A==
这是控制太打印的二维码  好像前面的链接地址是错误的
应该是这个吧
https://login.weixin.qq.com/qrcode/gdiDGrQX8A==

**Comment by HanSon** [comment]
一样的，微信网页端的版本不一样而已
