### ISSUE TITLE
Init failed

### ISSUE THREAD

**Issue by Smurfs-xxl** [HanSon/vbot#202]
[2017-08-07 06:41:59][INFO] please scan the qrCode with wechat.
[2017-08-07 06:42:06][INFO] please confirm login in wechat.
[2017-08-07 06:42:08][INFO] current session: e7b9c5
[2017-08-07 06:42:08][INFO] init begin.
[2017-08-07 06:42:08][INFO] current user's nickname:
[2017-08-07 06:42:08][INFO] current user's username:
[2017-08-07 06:42:08][INFO] current user's uin:0
PHP Fatal error:  Uncaught Hanson\Vbot\Exceptions\InitFailException: Init failed. in /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/Server.php:245
Stack trace:
#0 [internal function]: Hanson\Vbot\Core\Server->Hanson\Vbot\Core\{closure}(Array, 0, Array, Array, Array, '', '', 0, 0, 0, 0, 0, Array, 0)
#1 /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/ApiExceptionHandler.php(18): call_user_func_array(Object(Closure), Array)
#2 /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/Server.php(246): Hanson\Vbot\Core\ApiExceptionHandler::handle(Array, Object(Closure))
#3 /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/Server.php(38): Hanson\Vbot\Core\Server->init()
#4 /home/xxl/weixin-bot/Example.php(50): Hanson\Vbot\Core\Server->serve()
#5 /home/xxl/weixin-bot/run.php(9): Hanson\MyVbot\Example->run()
#6 {main}
  thrown in /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/Server.php on line 245
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Hanson\Vbot\Exceptions\InitFailException: Init failed. in /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/Server.php:245
Stack trace:
#0 [internal function]: Hanson\Vbot\Core\Server->Hanson\Vbot\Core\{closure}(Array, 0, Array, Array, Array, '', '', 0, 0, 0, 0, 0, Array, 0)
#1 /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/ApiExceptionHandler.php(18): call_user_func_array(Object(Closure), Array)
#2 /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/Server.php(246): Hanson\Vbot\Core\ApiExceptionHandler::handle(Array, Object(Closure))
#3 /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/Server.php(38): Hanson\Vbot\Core\Server->init()
#4 /home/xxl/weixin-bot/Example.php(50): Hanson\Vbot\Core\Server->serve()
#5 /home/xxl/weixin-bot/run.php(9): Hanson\MyVbot\Example->run()
#6 {main}
  thrown in /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/Server.php:245
Stack trace:
#0 {main}
  thrown in /home/xxl/weixin-bot/vendor/hanson/vbot/src/Core/Server.php on line 245

昨天运行正常，今天就出现这个错误，我试过在微信网页版是可以正常扫描登录，会到vbot就出现init failed。

**Comment by HanSon** [comment]
重新登录即可

**Comment by Smurfs-xxl** [comment]
重新登录微信App吗？

**Comment by HanSon** [comment]
重新跑脚本

**Comment by Smurfs-xxl** [comment]
试了5次，都是init failed

**Comment by Smurfs-xxl** [comment]
是不是网络问题，连nickname都取不到

**Comment by RoshanGH** [comment]
楼上问题解决了吗我也是

**Comment by RoshanGH** [comment]
重新跑的第5   6 次时好了。。。。
