### ISSUE TITLE
如何分享？在当前版本的Share类增加 use sendable是否可行

### ISSUE THREAD

**Issue by toeasy** [HanSon/vbot#213]
想通过API实现分享。看到Message的子类很多都可以是sendable 如Text,Card，而Share类不可以，加上sendable是否可行. 
另外Share的messageType是什么，在哪里能找到。

**Comment by HanSon** [comment]
web微信不支持，没找到发送分享的地方

在 share 部分的文档应该是有写的

**Comment by toeasy** [comment]
感谢及时解答。
我看了web微信确实没有分享。有没有其他思路实现分享呢
谢谢

**Comment by HanSon** [comment]
没有
