### ISSUE TITLE
新注册微信号无法登录网页版

### ISSUE THREAD

**Issue by chunyong1991** [HanSon/vbot#214]
![4b343acd-cb64-4fe9-a3d9-4b4f714a2195](https://user-images.githubusercontent.com/12395543/30465861-6b163c80-9a0c-11e7-9ae2-aad0040e3d25.jpeg)

机器人没法用了吗?

**Comment by HanSon** [comment]
最近封号有点厉害，特别是小号

**Comment by chunyong1991** [comment]
所以这只是个案吗？微信并没有禁用新帐号的网页版登录？

**Comment by HanSon** [comment]
不是个案，暂时没有有效的解决方法

**Comment by chunyong1991** [comment]
@HanSon  那么是不是可以说所有基于微信Web API的机器人都不支持新帐号了？

**Comment by HanSon** [comment]
不排除其他项目找到解决方案，你也可以尝试 python，如果他们的没事欢迎跟我说一下

**Comment by chunyong1991** [comment]
别的也悬，感觉上基于web api的都要跪，iPad协议又没人开源

**Comment by bear-shen** [comment]
嗯……现在这边的情况是老帐号也开始限制备注次数了……
大早产品瞎瘠薄推广一下冒出几百号人……现在备注全部报错……
