### ISSUE TITLE
扫描二维码后手机微信就显示一个二维码就完了。。。

### ISSUE THREAD

**Issue by zylx0532** [HanSon/vbot#216]
扫描二维码后手机微信就显示一个二维码就完了。。。

**Comment by HanSon** [comment]
请描述清楚问题

**Comment by zylx0532** [comment]
使用您提供的 MY-VBOT 或者 自己写RUN.PHP以及 基于您开发的 swoole-bot 
在控制台 php run.php 运行起来 能显示二维码
但是使用手机微信扫描二维码后 没有确认登录等提示
而是直接显示二维码图片在微信上。
有点像用微信打开一个图片URL的感觉

**Comment by HanSon** [comment]
已回退一个版本，试试用 2.0.6

**Comment by JingxuanZhang** [comment]
我也遇到这个问题，我今天比较了一下微信二维码解析出来的地址前缀是https://login.weixin.qq.com/l/，改完源码后可以登录了。希望大神核对一下是不是微信升级的原因。

**Comment by HanSon** [comment]
@JingxuanZhang 是修改 showQrCode 方法么？

**Comment by HanSon** [comment]
@JingxuanZhang 感谢，已修复，其实之前的链接还需要做其他的操作才可识别
