### ISSUE TITLE
cygwin64启用swoole，而swoole API 不管用 

### ISSUE THREAD

**Issue by rzl** [HanSon/vbot#222]
控制台没有报错。

发送消息
{"code":200,"result":{"BaseResponse":{"Ret":-1,"ErrMsg":""},"MsgID":"","LocalID":""}}

而使用获取好友的
{"code":200,"result":{"friends":null}}

**Comment by HanSon** [comment]
一般是传参有误

**Comment by rzl** [comment]
这样子应该是NickName含有b字母的应该都会返回吧？

![20171019160353](https://user-images.githubusercontent.com/4023376/31760487-6c5556bc-b4e7-11e7-96f5-75d306f48831.jpg)

**Comment by rzl** [comment]
我刚才试了一下又可以了。 谢谢 。

**Comment by ChinaBygones** [comment]
> 我刚才试了一下又可以了。 谢谢 。

你好，我和你一样的问题  请问你最后怎么解决的
