### ISSUE TITLE
出现不能识别的skey

### ISSUE THREAD

**Issue by ZoeSj** [HanSon/vbot#227]
扫描之后出现`vbot.ERROR: Undefined index: skey [] []``PHP Fatal error:  Uncaught ErrorException: Undefined index: skey in /usr/local/var/www/my-vbot/vendor/hanson/vbot/src/Core/Server.php:194`
但是我用之前的号扫描成功了，换个号刷新之后就不行了，有人遇到过吗?

**Comment by HanSon** [comment]
这个号被封了

**Comment by huanglike** [comment]
被封了是指这个微信号被封了？为什么？被谁封了？这是第一次扫描啊。
