### ISSUE TITLE
很容易被封号，建议大家用小号玩玩就行了~

### ISSUE THREAD

**Issue by zealerFT** [HanSon/vbot#229]
讲道理，很容易被封号，不知道是不是请求头原因，微信很容易就判断出是机器人，本来我想用来做个日志报警系统，但是小号测试完被封了，用自己号跑，也被封了。（当然封的是web端，不打电话给客服，不会自动解封）。慎用！！！！！！！！！！！！！！！！！！

**Comment by HanSon** [comment]
当前web协议都是这样，如果有更好的方式麻烦告知，谢谢

**Comment by shuyabin** [comment]
我看到其他的产品里面是使用ipad登录中.不知道是不是ipad那快做的限制比较少?
