### ISSUE TITLE
请问，扫码之后出现以下错误怎么解决。。。

### ISSUE THREAD

**Issue by i1219** [HanSon/vbot#232]
Redis已安装已运行

vbot.ERROR: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 in /www/web/test/vendor/illuminate/redis/RedisManager.php:40
Stack trace:
#0 /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 /www/web/test/vendor/illuminate/container/Container.php(749): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 /www/web/test/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /www/web/test/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('redis', Array)
#4 /www/web/test/vendor/illuminate/cont in /www/web/test/vendor/illuminate/redis/RedisManager.php on line 40

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 in /www/web/test/vendor/illuminate/redis/RedisManager.php:40
Stack trace:
#0 /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 /www/web/test/vendor/illuminate/container/Container.php(749): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 /www/web/test/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /www/web/test/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('redis', Array)
#4 /www/web/test/vendor/illuminate/cont in /www/web/test/vendor/illuminate/redis/RedisManager.php on line 40
[2017-12-07 04:58:36] vbot.ERROR: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 in /www/web/test/vendor/illuminate/redis/RedisManager.php:40 Stack trace: #0 /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL) #1 /www/web/test/vendor/illuminate/container/Container.php(749): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array) #2 /www/web/test/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure)) #3 /www/web/test/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('redis', Array) #4 /www/web/test/vendor/illuminate/cont [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 in /www/web/test/vendor/illuminate/redis/RedisManager.php:40
Stack trace:
#0 /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 /www/web/test/vendor/illuminate/container/Container.php(749): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 /www/web/test/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /www/web/test/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container- in /www/web/test/vendor/illuminate/redis/RedisManager.php on line 40

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 in /www/web/test/vendor/illuminate/redis/RedisManager.php:40
Stack trace:
#0 /www/web/test/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 /www/web/test/vendor/illuminate/container/Container.php(749): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 /www/web/test/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /www/web/test/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container- in /www/web/test/vendor/illuminate/redis/RedisManager.php on line 40

**Comment by HanSon** [comment]
redis 的配置有问题，或者改用 file做缓存

**Comment by i1219** [comment]
前面那个问题搞定了，扫码后出现这个问题，是不是https的问题？已经安装了curl-7.57.0，是不是还有什么东西没装，麻烦指点下菜鸟，谢谢！！
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxsendmsg?pass_ticket=xpjadq8wxX5WLTnEkT6NiiUB%2B3BysG626J5ioZLaaGcOsc7XMi99jdke84kp%2FRrVcURL error 35: A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by vincent-anlan** [comment]
@i1219 我也遇到相同问题了，请问您怎么解决的？

**Comment by HanSon** [comment]
关掉 swoole试试

**Comment by vincent-anlan** [comment]
谢谢啦

2017-12-28 1:06 GMT-05:00 HanSon <notifications@github.com>:
