### ISSUE TITLE
前面那个问题搞定了，扫码后出现这个问题，是不是https的问题？已经安装了curl-7.57.0，是不是还有什么东西没装，麻烦指点下菜鸟，谢谢！！

### ISSUE THREAD

**Issue by i1219** [HanSon/vbot#233]
前面那个问题搞定了，扫码后出现这个问题，是不是https的问题？已经安装了curl-7.57.0，是不是还有什么东西没装，麻烦指点下菜鸟，谢谢！！
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxsendmsg?pass_ticket=xpjadq8wxX5WLTnEkT6NiiUB%2B3BysG626J5ioZLaaGcOsc7XMi99jdke84kp%2FRrVcURL error 35: A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by HanSon** [comment]
see #205
