### ISSUE TITLE
报错！文件名已存在？？

### ISSUE THREAD

**Issue by YLJIOS** [HanSon/vbot#247]
[2018-03-09 05:35:10][ERROR] https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxsync?si
d=TVvIz9J6nceaTcjW&skey=@crypt_970d60d6_8d7a5020291b2908e65a53bb3d8fd696&lang=zh
_CN&pass_ticket=yUkoMV%2FGu9TBpXxNlHOtCAhUeoBWr%2Baq4aLZUd%2BIVzzFr86zrXIYqvkObP
yIn2vNcURL error 35: Unknown SSL protocol error in connection to wx2.qq.com:443
 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
PHP Fatal error:  Cannot use Hanson\Vbot\Support\File as File because the name i
s already in use in D:\phpStudy\WWW\wechat\vendor\hanson\vbot\src\Message\Emotic
on.php on line 14

**Comment by HanSon** [comment]
命名空间的问题，可自己解决
