### ISSUE TITLE
扫描登录，提示初始化失败

### ISSUE THREAD

**Issue by jy4618272** [HanSon/vbot#25]
![image](https://cloud.githubusercontent.com/assets/1615285/22365180/0d1007b2-e4b1-11e6-8b1e-815b1229dc75.png)

**Comment by jy4618272** [comment]
init修改为：
protected function init($first = true)
    {
        $url = sprintf($this->baseUri . '/webwxinit?r=%d&lang=zh_CN&pass_ticket=%s', ~(time()*1e3), $this->passTicket);

        $content = http()->json($url, [
            'BaseRequest' => $this->baseRequest
        ]);

        $result = json_decode($content, true);
        $this->generateSyncKey($result, $first);

        myself()->init($result['User']);

        $this->initContactList($result['ContactList']);

        if($result['BaseResponse']['Ret'] != 0){
            Console::log('初始化失败，链接：' . $url, Console::ERROR);
            exit;
        }
    }

**Comment by HanSon** [comment]
windows运行会出现这个问题，暂时还没找到解决办法

**Comment by Roland-Zhu** [comment]
1) Download cacert.pem file from here: http://curl.haxx.se/docs/caextract.html
2) Save the file in your PHP installation folder. (eg: If using xampp – save it in c:\Installation_Dir\xampp\php\cacert.pem).
3) Open your php.ini file and add this line:
4) curl.cainfo=”C:\Installation_Dir\xampp\php\cacert.pem”

**Comment by HanSon** [comment]
@Roland-Zhu You sure the problem with windows is because of cacert ?

**Comment by minirplus** [comment]
在Debian上运行也出现了这个问题，已经在其他地方登录过或者之前扫过程序的二维码登录但是没有在运行程序前退出而是在运行后退出的话，也出现了初始化失败的错误。

**Comment by oplain** [comment]
php版本换成7就可以了

**Comment by HanSon** [comment]
建议执行的PHP版本为PHP7，PHP7以下可能会发生未知的错误
