### ISSUE TITLE
升级依赖之后，扫码之后出错

### ISSUE THREAD

**Issue by kency** [Hanson/vbot#252]
composer upgrade的时候自动remove了这个
Removing symfony/debug (v4.0.6)
而且composer提示
Package aferrandini/phpqrcode is abandoned, you should avoid using it. Use endroid/qr-code instead.

在Hanson\Vbot\Foundation\ExceptionHandler.php里用到了这两个类，
use Symfony\Component\Debug\Exception\FatalErrorException;
use Symfony\Component\Debug\Exception\FatalThrowableError;
导致运行的时候，扫码之后提示
thrown in /workspace/localsite/vbot/vendor/hanson/vbot/src/Core/Server.php on line 247

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Hanson\Vbot\Exceptions\InitFailException: Init failed. in /workspace/localsite/vbot/vendor/hanson/vbot/src/Core/Server.php:247

**Comment by HanSon** [comment]
如果是 Init failed ，可以尝试多几次

**Comment by kency** [comment]
好了，我手贱composer.json多了逗号
