### ISSUE TITLE
example/hongbao.php  测试不成功

### ISSUE THREAD

**Issue by lijinma** [HanSon/vbot#26]
打印：`Console::log((int)($message instanceof RedPacket));` 一直是 0

你有跑通过吗？

**Comment by HanSon** [comment]
那是因为初始化也会接受很多其他类型的message，有试过发红包调试吗

**Comment by lijinma** [comment]
恩恩，试过的，除夕夜里试了很久，Text message 打印没问题，红包 message 一直没有打印成功过。

**Comment by lijinma** [comment]
`Console::log((int)($message instanceof RedPacket));`  我的意思是红包 message，一直都没有打印过1

**Comment by HanSon** [comment]
不知道理解有没有错误，当运行账号收到红包时，就会打印1

**Comment by lijinma** [comment]
@HanSon 理解没错。

我收到了若干信息，有文字信息，也有红包，但是打印这边一直是 0

**Comment by HanSon** [comment]
我这边测试过了，没有问题，再检查一下代码有没有其他地方报错吧
![image](https://cloud.githubusercontent.com/assets/10583423/22405823/5d163e2e-e683-11e6-800d-8b815b8ac152.png)
![image](https://cloud.githubusercontent.com/assets/10583423/22405831/68b038de-e683-11e6-8382-88b7d8ad99fd.png)

**Comment by lijinma** [comment]
@HanSon 好，我现在就再试试

**Comment by lijinma** [comment]
代码
```php
<?php
/**
 * Created by PhpStorm.
 * User: HanSon
 * Date: 2016/12/7
 * Time: 16:33
 */

require_once __DIR__ . './../vendor/autoload.php';

use Hanson\Vbot\Foundation\Vbot;
use Hanson\Vbot\Message\Entity\Message;
use Hanson\Vbot\Message\Entity\RedPacket;
use Hanson\Vbot\Support\Console;

$robot = new Vbot([
    'tmp' => __DIR__ . '/./../tmp/',
]);

$robot->server->setMessageHandler(function($message){
    /** @var $message Message */
    var_dump(get_class($message));
    if($message instanceof RedPacket){
        $nickname = account()->getAccount($message->from['UserName'])['NickName'];
        Console::log("收到来自 {$nickname} 的红包");
    }

});

$robot->server->run();
```

微信截图：

![file](https://dn-phphub.qbox.me/uploads/images/201701/30/77/5Kjs5peE7h.png)

打印截图：

![file](https://dn-phphub.qbox.me/uploads/images/201701/30/77/7xzos6tDbi.png)


现在看来，红包的 Message 没有打印出来。

**Comment by HanSon** [comment]
确认一下版本是否最新
