### ISSUE TITLE
请问可以实现从多个微信群拉取消息吗？

### ISSUE THREAD

**Issue by fishfree** [Hanson/vbot#269]
是不是必须是一个通过手机号等实际注册的微信账号，然后还得要加入要拉区信息的所有群，才能从这些群拉取消息？

**Comment by Hanson** [comment]
不是，登录了就可以了

**Comment by fishfree** [comment]
@Hanson 谢谢你！再问下哈：那是不是得把这个微信号加入了所有需要拉取消息的群里呢？
