### ISSUE TITLE
发送视频出错

### ISSUE THREAD

**Issue by edwinkoo** [Hanson/vbot#276]
调用：Video::send($sendTo, $message); 发送视频信息
报错：[ERROR] https://file.wx2.qq.com/cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

详细描述：
1. 视频mp4正确存在再 tmp相应目录下，且能正常打开
2. debug发现\Message\Message\TraitsMultimedia.php 第146行代码返回值 $result为空

请教解决方案，谢谢

**Comment by wangerzi** [comment]
我这边上传稍微大一点的图片或文件，比如2M就会报相同的错误，查了下web微信，看上去像是分段的，但是VBOT里边没有分段。

**Comment by edwinkoo** [comment]
@wangerzi 你说得没错。

$fp = fopen($file, "rb");
while (!feof($fp)) {
}
我将文件分片提交后，解决该问题了。

**Comment by Hanson** [comment]
@edwinkoo 求PR

**Comment by edwinkoo** [comment]
@Hanson 相关修改已发送到你邮箱h@hanc.cc，感谢你开源了这么好的项目，代码很棒！

**Comment by Hanson** [comment]
已修复
