### ISSUE TITLE
请教一下怎么在laravel中运行

### ISSUE THREAD

**Issue by ChinaBygones** [Hanson/vbot#281]
你好，请问在laravel中如何运行，自己尝试了很多次 依然不行 不知道怎么办了

**Comment by guoxiangke** [comment]
1. config/vbot.php 放置配置文件
2. php artisan make:command VbotStart
protected $signature = 'vbot:start {--session=}';

    public function handle()
    {
        $session = $this->option('session')?:null;
        $vbot = new Vbot($session);
        $vbot->start();
    }
3.
![image](https://user-images.githubusercontent.com/1160703/53226644-a9123000-36b6-11e9-8acb-5de2302ab17e.png)

**Comment by boySang** [comment]
> 1. config/vbot.php 放置配置文件
> 2. php artisan make:command VbotStart
>    protected $signature = 'vbot:start {--session=}';
>    public function handle()
>    {
>    $session = $this->option('session')?:null;
>    $vbot = new Vbot($session);
>    $vbot->start();
>    }
> 
> ![image](https://user-images.githubusercontent.com/1160703/53226644-a9123000-36b6-11e9-8acb-5de2302ab17e.png)

你知道咋在tp5里面运行吗？

**Comment by guoxiangke** [comment]
同理啊,只要你熟悉tp

**Comment by boySang** [comment]
> 同理啊,只要你熟悉tp

我熟悉常用的形式，但是不知道在命令行状态咋用哎。。
