### ISSUE TITLE
 Access level to Hanson\Vbot\Contact\Groups::add() must be public (as in class Illuminate\Support\Collection)

### ISSUE THREAD

**Issue by liyuexi** [Hanson/vbot#284]
PHP Fatal error:  Access level to Hanson\Vbot\Contact\Groups::add() must be public (as in class Illuminate\Support\Collection) in /Applications/XAMPP/xamppfiles/htdocs/vbot/vbot/vendor/hanson/vbot/src/Contact/Groups.php on line 303
是什么错 我查看了父类是public的呀 奇怪

**Comment by wangyuxiang147** [comment]
我也有这个问题你的解决了吗？

**Comment by guandaxia** [comment]
我把 `add()` 方法改成 `public` 就好了

**Comment by liyuexi** [comment]
后面解决了  看错了 看成contact的add方法了  是groups的add方法  改成public就行

**Comment by wangyuxiang147** [comment]
我也是把add() 方法改成 public

**Comment by limingxinleo** [comment]
https://github.com/Hanson/vbot/pull/285

**Comment by Hanson** [comment]
fix by #285
