### ISSUE TITLE
laravel5.5 使用 command 命令编写后 所有artisan命令都失效。

### ISSUE THREAD

**Issue by zxr615** [Hanson/vbot#313]
> 命令 wechat:defer
```php
protected $signature = 'wechat:defer';

public function handle()
    {
        // 收到消息时触发
        $this->messageHandler->setHandler(function ($message) {
            // 好友请求
             if ($message['type'] === 'request_friend') {

             }
        });

        $this->vbot->server->serve();
    }
```
> 正常情况
![image](https://user-images.githubusercontent.com/30486360/73677630-9fc87a80-46f1-11ea-803c-79555c7b899d.png)

> 问题所在，所有以 `php artisan `开头的命令全部都是运行 启动微信监听 的脚本
![image](https://user-images.githubusercontent.com/30486360/73677682-bc64b280-46f1-11ea-8fdb-951ba27218b6.png)

**Comment by Hanson** [comment]
不是很了解你是怎么改的，但可以肯定你一定改了 laravel 一些文件，例如 AppServiceProvider bootstrap.php kernel.php 等等。这些文件在执行 artisan 时候都会调用，可能你在这里面执行了 vbot 的程序
