### ISSUE TITLE
接收到文本消息程序异常退出

### ISSUE THREAD

**Issue by syw0602** [HanSon/vbot#42]
`Argument 2 passed to Hanson\Vbot\Message\Entity\Text::send() must be an instance of Hanson\Vbot\Message\Entity\string, string given, called in /Users/*****/www/wx/vendor/hanson/vbot/src/Core/MessageHandler.php on line 181 and defined in /Users/*****/www/wx/vendor/hanson/vbot/src/Message/Entity/Text.php on line 34
PHP Stack trace:
PHP   1. {main}() /Users/*****/www/wx/index.php:0
PHP   2. Hanson\Vbot\Core\Server->run() /Users/*****/www/wx/index.php:187
PHP   3. Hanson\Vbot\Core\MessageHandler->listen() /Users/*****/www/wx/vendor/hanson/vbot/src/Core/Server.php:93
PHP   4. Hanson\Vbot\Core\MessageHandler->handlerMessage($selector = '2') /Users/*****/www/wx/vendor/hanson/vbot/src/Core/MessageHandler.php:139
PHP   5. Hanson\Vbot\Message\Entity\Text::send($username = '@a930e571ef678d32344169d5b0269f40', $word = '334') /Users/*****/www/wx/vendor/hanson/vbot/src/Core/MessageHandler.php:181

Catchable fatal error: Argument 2 passed to Hanson\Vbot\Message\Entity\Text::send() must be an instance of Hanson\Vbot\Message\Entity\string, string given, called in /Users/*****/www/wx/vendor/hanson/vbot/src/Core/MessageHandler.php on line 181 and defined in /Users/*****/www/wx/vendor/hanson/vbot/src/Message/Entity/Text.php on line 34

Call Stack:
    0.0007     280008   1. {main}() /Users/*****/www/wx/index.php:0
    0.0172    1687072   2. Hanson\Vbot\Core\Server->run() /Users/*****/www/wx/index.php:187
   15.0523    6784608   3. Hanson\Vbot\Core\MessageHandler->listen() /Users/*****/www/wx/vendor/hanson/vbot/src/Core/Server.php:93
   30.0403    6794464   4. Hanson\Vbot\Core\MessageHandler->handlerMessage(string(1)) /Users/*****/www/wx/vendor/hanson/vbot/src/Core/MessageHandler.php:139
   31.5447    7003424   5. Hanson\Vbot\Message\Entity\Text::send(string(33), string(3)) /Users/*****/www/wx/vendor/hanson/vbot/src/Core/MessageHandler.php:181`

**Comment by HanSon** [comment]
你是不是用PHP5跑了一个不是最新的版本

**Comment by syw0602** [comment]
版本是 PHP 5.6.2
代码是 composer获取的

**Comment by HanSon** [comment]
已经发布了最新版本，你尝试用最新版本试试，PHP7的话就肯定不会有这问题
