### ISSUE TITLE
上传文件问题

### ISSUE THREAD

**Issue by yljphp** [HanSon/vbot#45]
自己也写过，到上传文件的时候就卡住了。。

**Comment by HanSon** [comment]
是什么类型的文件，下载是否成功，文件字节数是否为0

**Comment by yljphp** [comment]
说来惭愧，自己不会的就是uploadmediarequest参数中的值
```
https://github.com/HanSon/vbot/blob/df696b4f97358f6149e70bc291a65e7c1ace92f2/src/Message/UploadAble.php#L45
```

**Comment by HanSon** [comment]
你根据文件类型判断上传吧，分别对应 Image Emotion 等类都有对应的send方法

**Comment by HanSon** [comment]
与issue #56 相似，下版本解决

**Comment by HanSon** [comment]
fixed https://github.com/HanSon/vbot/pull/58/commits/6f2d5e9c49c1232dfe74a73b4bf8d1eff90114ae
