### ISSUE TITLE
建议做成服务的形式

### ISSUE THREAD

**Issue by star7th** [HanSon/vbot#46]
这个项目挺好玩的。希望可以做一些改善让其变得更加实用。
比如，写开放API，将vbot做成一个服务——这个服务只负责收发微信消息。这样做的好处是与业务代码彻底分离，便于业务的独立编写。业务独立后，也更加自由。比如说我写一个web端的管理系统，当想推送微信消息的时候直接调用vbot 的api，而不需要引进vbot的代码进我的业务代码里，也不需要命令行里执行php

**Comment by star7th** [comment]
其实我本来是想着自己有时间就改写下，将vbot改成收发微信消息的服务。发觉自己很难挤出时间，同时也想了下这个需求可能是大众需求，所以来建议下作者改写了。看你有没有时间。如果你也忙的话，或者觉得这个需求是可忽略的小众需求话，那我迟点有时间自己写，然后再开源

**Comment by HanSon** [comment]
其实这个我也有计划，当时间问题一直挤不出时间

**Comment by HanSon** [comment]
做这个并不难，加多个监听器监听队列即可

**Comment by luohow** [comment]
这个多开会被微信封杀了吧

**Comment by HanSon** [comment]
@star7th 这个在2.0版本会增加

**Comment by HanSon** [comment]
@luohow 不会，封杀还是取决于 “跟机器人行为相似度” ，如果频繁调用API，是会封一段时间，至于永久封闭还不清楚

**Comment by jerecao** [comment]
@HanSon 做成服务的方式，相当于vbot部署在服务器端，这样会不会造成同一个或几个ip登录太多的微信号，增加封号的风险？

**Comment by wikimo** [comment]
对这个话题也感兴趣。服务形式对于服务器资源占用是不是比较大，比如开100个，目前的方式本地运行开个几个还是没什么压力的。 @HanSon

**Comment by HanSon** [comment]
@wikimo 这个其实压力并不大

@jerecao 这个没有具体测试我也测试不了，但一个办公室出网IP都是同一个的了，多个理论上也不是问题

**Comment by HanSon** [comment]
@star7th API也已实现

**Comment by greedying** [comment]
赞！

**Comment by huanglike** [comment]
@star7th  @HanSon  两位大佬，距离你们最开始讨论要封装独立的API 已经过去半年有余了，不知道我是否足够幸运，已经可以用到你们的改进版本了呢！
