### ISSUE TITLE
请问如何以守护进程的方式，在后台持续运行

### ISSUE THREAD

**Issue by BEIBEI123** [HanSon/vbot#55]
希望程序运行在服务器，做群管理，当ssh关闭时希望程序不会结束

**Comment by HanSon** [comment]
nohup php demo.php > run.log 2>&1 &

**Comment by JanHuang** [comment]
@BEIBEI123 其实用我的那个组件也行，或者用swoole那个Process也可以的。

```
composer require fastd/swoole
```

```php
$process = new Process('vbot', function () {
    $vbot = new Example();

    $vbot->run();
});
$process->daemon();
$process->start();
```

**Comment by leubao** [comment]
nohup php demo.php > run.log 2>&1 &  终端没有输出二维码登录不了啊

**Comment by shouhuori** [comment]
@leubao 有提供[监听器](http://create.hanc.cc/vbot/docs/observer.html)，监听登录方法，得到二维码链接，可以使用`print_r()`打印出来，它会出现在`run.log`中。我是存到redis里给其他程序用来生成二维码了
