### ISSUE TITLE
表情上传失败

### ISSUE THREAD

**Issue by dormscript** [HanSon/vbot#56]
Array
(
    [BaseResponse] => Array
        (
            [Ret] => 1100
            [ErrMsg] => 
        )

    [MediaId] => 
    [StartPos] => 0
    [CDNThumbImgHeight] => 0
    [CDNThumbImgWidth] => 0
)

[2017-03-24 10:53:40][WARNING] 表情 /webroot/src/vbot/tmp/@caabae28c2663172d198f72676b065bf/gif/82602446872838730.gif 上传失败

**Comment by HanSon** [comment]
部分表情是需要去表情商城自行下载才能使用，这是下载表情失败的原因
也是上传失败的原因，你可以看看这个文件，应该只有 0 字节

**Comment by dormscript** [comment]
这个文件能正常打开，不是0字节

**Comment by HanSon** [comment]
已发现问题所在，预估下个版本修复

**Comment by dormscript** [comment]
真棒

**Comment by HanSon** [comment]
fixed https://github.com/HanSon/vbot/pull/58/commits/6f2d5e9c49c1232dfe74a73b4bf8d1eff90114ae
