### ISSUE TITLE
load_string()问题?

### ISSUE THREAD

**Issue by kyaky** [HanSon/vbot#62]
[2017-03-29 09:39:58][INFO] 请扫描二维码登录
[2017-03-29 09:40:04][INFO] 请点击确认登录微信
PHP Fatal error:  Uncaught Error: Call to undefined function Hanson\Vbot\Core\simplexml_load_string() in /root/vendor/hanson/vbot/src/Core/Server.php:243
Stack trace:
#0 /root/vendor/hanson/vbot/src/Core/Server.php(139): Hanson\Vbot\Core\Server->login()
#1 /root/vendor/hanson/vbot/src/Core/Server.php(81): Hanson\Vbot\Core\Server->prepare()
#2 /root/vendor/hanson/vbot/example/index.php(213): Hanson\Vbot\Core\Server->run()
#3 {main}
  thrown in /root/vendor/hanson/vbot/src/Core/Server.php on line 243
root@ubuntu:~/vendor/hanson/vbot#

**Comment by HanSon** [comment]
请安装 SimpleXML 拓展 
http://php.net/manual/zh/book.simplexml.php
