### ISSUE TITLE
运行5分钟有内就出错

### ISSUE THREAD

**Issue by kyaky** [HanSon/vbot#63]
我在digitalocean的vps运行的。。。 是因为美西的vps延迟问题吗？ 还是怎么回事。。。

PHP Fatal error:  Uncaught RuntimeException: Error creating resource: [message] fopen(http://www.tuling123.com/openapi/api): failed to open stream: Connection timed out
[file] /root/vendor/hanson/vbot/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 322 in /root/vendor/hanson/vbot/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252
Stack trace:
#0 /root/vendor/hanson/vbot/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(333): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /root/vendor/hanson/vbot/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /root/vendor/hanson/vbot/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(72): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /root/vendor/hanson/vbot/vendor/guzzlehttp/guzzle/src/Middleware.php(36): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /root/vendo in /root/vendor/hanson/vbot/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 52

**Comment by HanSon** [comment]
这个是调用图灵时报错，加try catch即可
