### ISSUE TITLE
如何指定转发到特定群?

### ISSUE THREAD

**Issue by kyaky** [HanSon/vbot#67]
请问那个函数可以做到, 把A群某个人说的话, 转到B群? 如何制定发送信息的目的地. 

谢谢

**Comment by HanSon** [comment]
其实与函数没有太多关系，无非是 Text::send() 或者 Image::send 等

重点是你得知道这个消息是否你想要转发的对象，做好一些判断即可

**Comment by kyaky** [comment]
这个转发 没啥问题... 我想知道 怎么发到特定的群里...

**Comment by kyaky** [comment]
通常不是 哪里接收的信息 就send()就回复到哪里么... 如何定向发到一个群里...

**Comment by HanSon** [comment]
group()->getUsername('群名称', 'NickName'); 这就是你要发的username了

**Comment by kyaky** [comment]
谢谢老板! 我去试试... 我以为send()的参数必须是人的id呢 原来也可以是群的...
