### ISSUE TITLE
能不能提供一个主动添加好友的方法？

### ISSUE THREAD

**Issue by mkanako** [HanSon/vbot#70]
一个机器人号设置了加好友无需验证，这样加好友后，无双方发消息是没问题的，但是机器人号通讯录里却没有对方账号，如果对方给机器人号转账就会提示“你不是收款方的好友”

**Comment by HanSon** [comment]
不是很理解，那手机如何操作才可以？

**Comment by mkanako** [comment]
![image](http://wx2.sinaimg.cn/large/94e640d3gy1fe55hwc6q7j20m80zk76c.jpg)
聊天窗口上方有一个添加好友提示，添加一下就好了

**Comment by HanSon** [comment]
重点是这种情况需要如何才能重现。。不然很难测试

**Comment by mkanako** [comment]
咦，难道你重现不出来？机器人号设置添加好友无需验证，然后自己的号添加机器人号为好友，自动通过，双方可以发消息，但这时候你的通讯录里面有机器人的号，但是机器人通讯录里没有你的号，用机器人号去跟你聊天就会这样上图那种情况

**Comment by mkanako** [comment]
A设置了添加好友无需验证后，B添加A为好友，这时A是B的好友，但是B却不是A的好友，需要A主动添加一下B，双方才是互为好友

**Comment by HanSon** [comment]
这种情况的确没玩过，有空我测试一下

**Comment by DavidFnck** [comment]
同样是遇到这个问题，描述：

在 vbot 设置添加好友无需验证时候（我->设置->隐私的第一个开关），那些申请添加的好友可以立即开始聊天，但是还不是互为好友，回复「拉我」，就无法触发拉群操作。只有当 vbot 手动点添加好友的时候，才会完成这个操作。

**Comment by DavidFnck** [comment]
同样是遇到这个问题，描述：

在 vbot 设置添加好友无需验证时候（我->设置->隐私的第一个开关），那些申请添加的好友可以立即开始聊天，但是还不是互为好友，回复「拉我」，就无法触发拉群操作。只有当 vbot 手动点添加好友的时候，才会完成这个操作。

我刚刚用 Mac 微信客户端测试了，也是扫码登录，在手机端设置无需验证的时候，Mac 端可以搜到这个添加者的信息，但是通讯录不会发生变化，也就是这个人还不是我的好友，但是因为我的微信无需验证，是开放状态，所以可以直接聊，需要手动再添加一下。

**Comment by DavidFnck** [comment]
同样是遇到这个问题，描述：

在 vbot 设置添加好友无需验证时候（我->设置->隐私的第一个开关），那些申请添加的好友可以立即开始聊天，但是还不是互为好友，回复「拉我」，就无法触发拉群操作。只有当 vbot 手动点添加好友的时候，才会完成这个操作。

我刚刚用 Mac 微信客户端测试了，也是扫码登录，在手机端设置无需验证的时候，Mac 端可以搜到这个添加者的信息，但是通讯录不会发生变化，也就是这个人还不是我的好友，但是因为我的微信无需验证，是开放状态，所以可以直接聊，需要手动再添加一下。

问题：这个环节的不自动化，直接影响到拉群的自动化，操作者依然要点至少两步。

解决思路：

1. 设置无需验证，看看能不能在收到好友添加的情况下载，自动添加好友，但是因为 Mac 端是没有显示的，我担心可能程序上没有这个接口。

2. 设置需要验证，则 Mac 端微信会收到好友申请，同时会有「通过验证」的按钮，这个按钮就会允许用户成为好友，能够自动化这个过程，也就解决了上面这个问题。

不知道能不能实现？有阐述不清楚的地方，欢迎随时交流。希望有更好的方法。

**Comment by HanSon** [comment]
@DavidFnck 这个暂时不予以解决
