### ISSUE TITLE
手机端@机器人会有有个口字符在后面

### ISSUE THREAD

**Issue by kyaky** [HanSon/vbot#72]
[MESSAGE] [2024326183743707073] @49的小奴猫口

如果是电脑端@就不会有这个口符号

这样会导致灵图机器人手机端无法识别问题 电脑端可以识别

**Comment by kyaky** [comment]
![20170331135932](https://cloud.githubusercontent.com/assets/5505790/24534543/68a2f61c-161a-11e7-9b1d-135b36bb1255.png)

**Comment by HanSon** [comment]
已发现问题，手机跟电脑的空格不太一样，一个是全角一个是半角

稍后修复

**Comment by HanSon** [comment]
fixed https://github.com/HanSon/vbot/commit/e2cbf9fafdf1a7ebae2dcd8fa54ccdd22b96180c
