### ISSUE TITLE
托管一段时间后，会自动掉线

### ISSUE THREAD

**Issue by wangyupeng** [HanSon/vbot#8]
托管一段时间后（几个小时后，或几天后），会自动掉线。你遇到过这种问题吗？

**Comment by HanSon** [comment]
托管了多久，期间有没有报错？有没有其他客户端登录？

**Comment by HanSon** [comment]
vbot 的持久性于 2017/1/21 00:36 分开始测试，并趁着春节这段时间测试持久性，春节后也会公布测试结果

**Comment by KevinGong2013** [comment]
609776708

**Comment by HanSon** [comment]
@KevinGong2013 大兄弟，你这样砸场子不太好吧🙄

**Comment by KevinGong2013** [comment]
@HanSon 没关系， 完全不同的技术哈哈～

**Comment by HanSon** [comment]
你的是手机端的协议吧

**Comment by KevinGong2013** [comment]
web端协议为主，web实现不了就代理到手机

**Comment by HanSon** [comment]
@wangyupeng 

如何长时间免手机端挂机：
1、正常的扫码登录机器人
2、关闭WIFI和移动数据开关（保持手机断网状态
3、打开手机微信，退出登录（等待10秒左右会自动退出）
4、开启移动数据开关或者连接WIFI。
5、换其他微信登录。
目前已经是第三天

这是群里群友发的

**Comment by wangyupeng** [comment]
好的，学习下
